/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package leaner;
import java.io.File;
import java.util.*;
import java.nio.file.Path;
import java.io.IOException;




public class App {
    public static void main(String[] args) {
        Path myfile = Path.of("app/src/main/resources/gate.js");
        App MyFile = new App();
        System.out.println(MyFile.linter(myfile));
    }
/////////////////////////////////////////////////////////////////////////////////
//////////////////////  linter   ///////////////////////////////////////////////
/////////////////////////////////////////////////////////////////////////////////

    public String linter(Path path) {

        StringBuilder error = new StringBuilder();
        int count= 0;

        try {
            File file = new File(path.toUri());
            Scanner scan = new Scanner(file);

            while (scan.hasNextLine()) {
                count++;
                String dataInFile = scan.nextLine();
                if (!dataInFile.endsWith(";") && !dataInFile.endsWith("}") && !dataInFile.endsWith("{") && !dataInFile.contains("else") && !dataInFile.contains("if") && !dataInFile.isEmpty() ) {
                    error.append(count).append(" You Miss  ; \n");
                }
            }
            scan.close();
        } catch (IOException e) {
            System.out.println(e.getMessage());
        }


        return error.toString();
    }

}
